type: application

workspace:
  inheritedTasks:
    exclude: [buildPackage]

tasks:
  build:
    command: next
    args: build
  dev:
    command: next
    args: dev
    options:
      runInCI: false
  start:
    command: next
    args: start
    options:
      runInCI: false
