$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  # https://moonrepo.dev/docs/guides/examples/packemon
  build:
    command:
      - 'packemon'
      - 'pack'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
      - '--declarationConfig'
      - 'tsconfig.build.json'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.build.json'
    outputs:
      - 'dts'
    env:
      NODE_ENV: 'production'
