$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  # https://moonrepo.dev/docs/guides/examples/packemon
  build:
    command:
      - 'packemon'
      - 'pack'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
